version: '3'
services:
    dbclient:
        image: postgres:12.0
        depends_on:
            - db
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - "./backups:/backups"
